import { useState } from 'react';
import { useHistory } from 'react-router-dom';


const Create = () => {

    const [title, setTitle] = useState('');
    const [body, setBody] = useState('');
    const [author, setAuthor] = useState('mario');
    const [isPending, setIsPending] = useState(false);
    const history = useHistory();

    const handleSubmit = (e) => {
        e.preventDefault();
        const blog = { title, body, author };  // id is auto generated by json-server

        setIsPending(true);

        console.log(blog);
        fetch('http://localhost:8000/blogs', {
            method: 'POST',
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify(blog)
        }).then( () => {
            console.log(blog.title + " added!");
            setTimeout(() => {
                setIsPending(false);
                //history.go(-1);  // go back one page prior
                history.push('/');  // redirect user to homepage
            }, 1000);
        })
    }

    return ( 
        <div className="create">
            <h2>Create a new blog!</h2>
            <form onSubmit={handleSubmit}>
                <label>Blog title:</label>
                <input 
                    type="text"
                    required
                    value={ title }
                    onChange={(e) => setTitle(e.target.value)}
                />
                <label>Blog body:</label>
                <textarea
                    required
                    value={body}
                    onChange={(e) => setBody(e.target.value)}
                />
                <label>Blog author:</label>
                <select
                    value={author}
                    onChange={(e) => setAuthor(e.target.value)}
                >
                    <option value="mario">mario</option>
                    <option value="luigi">luigi</option>
                    <option value="yoshi">yoshi</option>
                </select>
                { !isPending && <button>Add blog!</button> }
                { isPending && <button disabled>Adding...</button> }
                {/* <button>Cancel</button> */}
            </form>
        </div>
     );
}
 
export default Create;